/**
 * Project TRIDENT — Mock Data Fallbacks
 * 
 * Provides offline/initial demonstration state representing the canonical
 * 14-day master demo, 6 hackathon beats, and privacy governance mechanisms.
 */

import {
  CanaryDecoy,
  CausalEdge,
  CausalNode,
  ForensicDossier,
  HarassmentAlert,
  PrivacyVaultStatus,
  ProtectedRule,
  RevealReceipt,
  ScenarioDaySnapshot,
  ScenarioMetadata,
} from "./types";

export const MOCK_SCENARIOS: ScenarioMetadata[] = [
  {
    scenario_id: "MASTER_DEMO",
    title: "14-Day Master Demo (Low & Slow Insider)",
    name: "Master Hackathon 14-Day Trajectory",
    description: "Canonically demonstrates all 6 hackathon demo beats from stable baseline to canary confirmation.",
    duration_days: 14,
    threat_type: "LOW_AND_SLOW_INSIDER",
    expected_tier: "TIER_4_CRITICAL",
    mitre_tactics: ["Initial Access", "Privilege Escalation", "Discovery", "Collection", "Exfiltration"],
  },
  {
    scenario_id: "SCENARIO_A",
    title: "Scenario A: Legitimate Role Change",
    name: "Legitimate Role Transition",
    description: "High volume data anomaly fully attenuated by valid organizational change request.",
    duration_days: 14,
    threat_type: "BENIGN_ROLE_CHANGE",
    expected_tier: "TIER_1_CONTEXTUAL_DRIFT",
    mitre_tactics: ["Defense Evasion"],
  },
  {
    scenario_id: "SCENARIO_B",
    title: "Scenario B: Low-and-Slow Insider",
    name: "Sub-Threshold Lateral Movement",
    description: "Persistent sub-threshold displacement accumulating severe recursive CUSUM drift.",
    duration_days: 14,
    threat_type: "INSIDER_DATA_THEFT",
    expected_tier: "TIER_3_HIGH_RISK",
    mitre_tactics: ["Discovery", "Collection"],
  },
  {
    scenario_id: "SCENARIO_C",
    title: "Scenario C: Fabricated Context Attack",
    name: "Phantom Ticket Context Poisoning",
    description: "Self-approved phantom Jira ticket rejected by 10-signal CAS engine with zero attenuation.",
    duration_days: 14,
    threat_type: "CONTEXT_POISONING",
    expected_tier: "TIER_3_HIGH_RISK",
    mitre_tactics: ["Defense Evasion", "Collection"],
  },
  {
    scenario_id: "SCENARIO_D",
    title: "Scenario D: Emergency Incident Access",
    name: "Out-of-Band PagerDuty Emergency",
    description: "High severity PagerDuty incident grants temporary discounted production access window.",
    duration_days: 14,
    threat_type: "EMERGENCY_ACCESS",
    expected_tier: "TIER_2_UNANCHORED_EXPLORATION",
    mitre_tactics: ["Privilege Escalation"],
  },
  {
    scenario_id: "SCENARIO_E",
    title: "Scenario E: Compromised Service Account",
    name: "CI/CD Runner Credential Abuse",
    description: "Non-human automated identity hijacking with off-hours geographic discrepancy.",
    duration_days: 14,
    threat_type: "CREDENTIAL_COMPROMISE",
    expected_tier: "TIER_4_CRITICAL",
    mitre_tactics: ["Initial Access", "Privilege Escalation", "Exfiltration"],
  },
];

export const MOCK_TIMELINE_SNAPSHOTS: ScenarioDaySnapshot[] = [
  {
    day: 1,
    timestamp: "2026-09-01T08:00:00Z",
    raw_anomaly_score: 6.0,
    context_authenticity_score: 0.88,
    discount_factor: 0.18,
    attenuated_anomaly_score: 1.2,
    cusum_drift_score: 0.0,
    drift_velocity: 0.0,
    trajectory_state: "STABLE",
    composite_risk: 1.2,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 2,
    timestamp: "2026-09-02T08:00:00Z",
    raw_anomaly_score: 7.5,
    context_authenticity_score: 0.86,
    discount_factor: 0.19,
    attenuated_anomaly_score: 1.5,
    cusum_drift_score: 0.0,
    drift_velocity: 0.0,
    trajectory_state: "STABLE",
    composite_risk: 1.5,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 3,
    timestamp: "2026-09-03T08:00:00Z",
    raw_anomaly_score: 8.0,
    context_authenticity_score: 0.85,
    discount_factor: 0.20,
    attenuated_anomaly_score: 1.6,
    cusum_drift_score: 0.0,
    drift_velocity: 0.0,
    trajectory_state: "STABLE",
    composite_risk: 1.6,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 4,
    timestamp: "2026-09-04T08:00:00Z",
    raw_anomaly_score: 9.2,
    context_authenticity_score: 0.84,
    discount_factor: 0.21,
    attenuated_anomaly_score: 2.0,
    cusum_drift_score: 0.05,
    drift_velocity: 0.05,
    trajectory_state: "STABLE",
    composite_risk: 2.0,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 5,
    timestamp: "2026-09-05T08:00:00Z",
    raw_anomaly_score: 74.0,
    context_authenticity_score: 0.82,
    discount_factor: 0.22,
    attenuated_anomaly_score: 16.3,
    cusum_drift_score: 0.12,
    drift_velocity: 0.07,
    trajectory_state: "STABLE",
    composite_risk: 16.3,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: ["T1078"],
  },
  {
    day: 6,
    timestamp: "2026-09-06T08:00:00Z",
    raw_anomaly_score: 10.0,
    context_authenticity_score: 0.85,
    discount_factor: 0.20,
    attenuated_anomaly_score: 2.2,
    cusum_drift_score: 0.10,
    drift_velocity: -0.02,
    trajectory_state: "STABLE",
    composite_risk: 2.2,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 7,
    timestamp: "2026-09-07T08:00:00Z",
    raw_anomaly_score: 12.0,
    context_authenticity_score: 0.80,
    discount_factor: 0.25,
    attenuated_anomaly_score: 3.0,
    cusum_drift_score: 0.18,
    drift_velocity: 0.08,
    trajectory_state: "STABLE",
    composite_risk: 3.0,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 8,
    timestamp: "2026-09-08T08:00:00Z",
    raw_anomaly_score: 15.0,
    context_authenticity_score: 0.70,
    discount_factor: 0.35,
    attenuated_anomaly_score: 5.3,
    cusum_drift_score: 0.45,
    drift_velocity: 0.27,
    trajectory_state: "STABLE",
    composite_risk: 5.3,
    risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    canary_state: "ARMED",
    active_mitre_tactics: [],
  },
  {
    day: 9,
    timestamp: "2026-09-09T08:00:00Z",
    raw_anomaly_score: 38.0,
    context_authenticity_score: 0.0,
    discount_factor: 1.0,
    attenuated_anomaly_score: 38.0,
    cusum_drift_score: 1.25,
    drift_velocity: 0.80,
    trajectory_state: "INITIAL_DRIFT",
    composite_risk: 38.0,
    risk_tier: "TIER_2_UNANCHORED_EXPLORATION",
    canary_state: "ARMED",
    active_mitre_tactics: ["T1078", "T1083"],
  },
  {
    day: 10,
    timestamp: "2026-09-10T08:00:00Z",
    raw_anomaly_score: 68.0,
    context_authenticity_score: 0.21,
    discount_factor: 0.88,
    attenuated_anomaly_score: 59.8,
    cusum_drift_score: 2.35,
    drift_velocity: 1.10,
    trajectory_state: "PERSISTENT_DRIFT_ESCALATION",
    composite_risk: 59.8,
    risk_tier: "TIER_3_HIGH_RISK",
    canary_state: "ARMED",
    active_mitre_tactics: ["T1078", "T1083", "T1068"],
  },
  {
    day: 11,
    timestamp: "2026-09-11T08:00:00Z",
    raw_anomaly_score: 62.0,
    context_authenticity_score: 0.15,
    discount_factor: 0.92,
    attenuated_anomaly_score: 57.0,
    cusum_drift_score: 3.15,
    drift_velocity: 0.80,
    trajectory_state: "PERSISTENT_DRIFT_ESCALATION",
    composite_risk: 64.5,
    risk_tier: "TIER_3_HIGH_RISK",
    canary_state: "ARMED",
    active_mitre_tactics: ["T1078", "T1005"],
  },
  {
    day: 12,
    timestamp: "2026-09-12T08:00:00Z",
    raw_anomaly_score: 78.0,
    context_authenticity_score: 0.08,
    discount_factor: 0.95,
    attenuated_anomaly_score: 74.1,
    cusum_drift_score: 3.90,
    drift_velocity: 0.75,
    trajectory_state: "PERSISTENT_DRIFT_ESCALATION",
    composite_risk: 74.1,
    risk_tier: "TIER_3_HIGH_RISK",
    canary_state: "ARMED",
    active_mitre_tactics: ["T1078", "T1005", "T1074"],
  },
  {
    day: 13,
    timestamp: "2026-09-13T08:00:00Z",
    raw_anomaly_score: 92.0,
    context_authenticity_score: 0.0,
    discount_factor: 1.0,
    attenuated_anomaly_score: 92.0,
    cusum_drift_score: 4.55,
    drift_velocity: 0.65,
    trajectory_state: "CRITICAL_BREACH_CONFIRMED",
    composite_risk: 92.0,
    risk_tier: "TIER_4_CRITICAL",
    canary_state: "CONFIRMED",
    active_mitre_tactics: ["T1078", "T1005", "T1074"],
  },
  {
    day: 14,
    timestamp: "2026-09-14T08:00:00Z",
    raw_anomaly_score: 96.0,
    context_authenticity_score: 0.0,
    discount_factor: 1.0,
    attenuated_anomaly_score: 96.0,
    cusum_drift_score: 5.12,
    drift_velocity: 0.57,
    trajectory_state: "CRITICAL_BREACH_CONFIRMED",
    composite_risk: 96.0,
    risk_tier: "TIER_4_CRITICAL",
    canary_state: "CONFIRMED",
    active_mitre_tactics: ["T1078", "T1068", "T1083", "T1005", "T1074", "T1567"],
  },
];

export const MOCK_CAUSAL_NODES: CausalNode[] = [
  { id: "node-actor", label: "Subject-Theta-482", category: "ACTOR", sensitivity: 0.3 },
  { id: "node-cred", label: "role:prod-engineer-admin", category: "CREDENTIAL", sensitivity: 0.75 },
  { id: "node-repo", label: "repo:core-payment-gateway", category: "DISCOVERY", sensitivity: 0.6 },
  { id: "node-db", label: "db:customer-pii-production", category: "DATABASE", sensitivity: 0.95 },
  { id: "node-staging", label: "staging:/dev/shm/dump.tar.gz", category: "DISCOVERY", sensitivity: 0.85 },
  { id: "node-canary", label: "arn:aws:s3:::canary-decoy-payroll-backup", category: "CANARY", sensitivity: 1.0 },
];

export const MOCK_CAUSAL_EDGES: CausalEdge[] = [
  { id: "e1", source: "node-actor", target: "node-cred", edge_type: "ASSUMED_ROLE", sensitivity: 0.75 },
  { id: "e2", source: "node-actor", target: "node-repo", edge_type: "QUERIED", sensitivity: 0.6 },
  { id: "e3", source: "node-actor", target: "node-db", edge_type: "ACCESSED", sensitivity: 0.95 },
  { id: "e4", source: "node-actor", target: "node-staging", edge_type: "STAGED", sensitivity: 0.85 },
  { id: "e5", source: "node-actor", target: "node-canary", edge_type: "CANARY_TRIP", sensitivity: 1.0, is_canary_trip: true },
];

export const MOCK_CANARY_STATUS: CanaryDecoy = {
  canary_id: "CANARY-DECOY-S3-01",
  resource_id: "arn:aws:s3:::canary-decoy-payroll-backup",
  resource_type: "AWS_S3_BUCKET",
  created_at: "2026-09-01T00:00:00Z",
  is_tripped: true,
  confirmation_state: "CONFIRMED",
  trip_timestamp: "2026-09-13T03:12:44Z",
  tripped_by_actor: "Subject-Theta-482",
  predicted_threat_actor: "Subject-Theta-482",
  deployment_location: "us-east-1 / VPC-prod-internal / S3",
  claim_label: "Simulated Canary",
};

export const MOCK_FORENSIC_DOSSIER: ForensicDossier = {
  incident_id: "INC-TRIDENT-2026-09-14",
  subject_token: "Subject-Theta-482",
  risk_tier: "TIER_4_CRITICAL",
  composite_risk: 96.0,
  trajectory_state: "CRITICAL_BREACH_CONFIRMED",
  cusum_drift_score: 5.12,
  context_justification_claimed: true,
  context_authenticity_score: 0.18,
  anchor_discount_factor: 0.85,
  context_failure_reasons: [
    "Temporal Mismatch: Ticket created 4m prior to access (-0.90)",
    "Approver Conflict: Self-approved ticket JIRA-OPS-992 (-1.00)",
    "Ghost Ticket: Zero downstream commits or deploy artifacts (-0.95)",
  ],
  progression_chain: [
    {
      step_number: 1,
      technique: "T1078 Valid Accounts",
      timestamp: "Day 9 08:30 UTC",
      action: "Session token anomaly without ticket anchor",
      source_entity: "Subject-Theta-482",
      target_entity: "role:prod-engineer-admin",
      evidence_confidence: 0.95,
      is_canary_trip: false,
    },
    {
      step_number: 2,
      technique: "T1083 File Discovery",
      timestamp: "Day 10 14:15 UTC",
      action: "Targeted codebase search for database credentials",
      source_entity: "Subject-Theta-482",
      target_entity: "repo:core-payment-gateway",
      evidence_confidence: 0.92,
      is_canary_trip: false,
    },
    {
      step_number: 3,
      technique: "T1005 Local Data Collection",
      timestamp: "Day 11 19:40 UTC",
      action: "Mass SQL query execution against payroll tables",
      source_entity: "Subject-Theta-482",
      target_entity: "db:customer-pii-production",
      evidence_confidence: 0.98,
      is_canary_trip: false,
    },
    {
      step_number: 4,
      technique: "T1074 Data Staged",
      timestamp: "Day 12 23:10 UTC",
      action: "Archive staging to volatile memory partition /dev/shm",
      source_entity: "Subject-Theta-482",
      target_entity: "staging:/dev/shm/dump.tar.gz",
      evidence_confidence: 0.94,
      is_canary_trip: false,
    },
    {
      step_number: 5,
      technique: "T1078 Canary Decoy Access",
      timestamp: "Day 13 03:12 UTC",
      action: "Decoy honey-bucket accessed; threat confirmation resolved to CONFIRMED",
      source_entity: "Subject-Theta-482",
      target_entity: "arn:aws:s3:::canary-decoy-payroll-backup",
      evidence_confidence: 1.0,
      is_canary_trip: true,
    },
  ],
  mitre_attack_matrix: [
    {
      technique_id: "T1078",
      technique_name: "Valid Accounts",
      tactic: "Initial Access & Defense Evasion",
      description: "Adversaries abuse credentials of existing accounts as a means of gaining initial access and defense evasion.",
    },
    {
      technique_id: "T1068",
      technique_name: "Exploitation for Privilege Escalation",
      tactic: "Privilege Escalation",
      description: "Adversaries exploit software vulnerabilities or assume privileged IAM roles to gain elevated access.",
    },
    {
      technique_id: "T1087",
      technique_name: "Account Discovery",
      tactic: "Discovery",
      description: "Adversaries attempt to get a listing of accounts to identify high-privilege targets.",
    },
    {
      technique_id: "T1083",
      technique_name: "File and Directory Discovery",
      tactic: "Discovery",
      description: "Adversaries enumerate files or query repository listings to discover sensitive data stores.",
    },
    {
      technique_id: "T1005",
      technique_name: "Data from Local System",
      tactic: "Collection",
      description: "Adversaries search for and access sensitive data from databases, repositories, or local file systems prior to exfiltration.",
    },
    {
      technique_id: "T1074",
      technique_name: "Data Staged",
      tactic: "Collection",
      description: "Adversaries stage collected data in a central location prior to exfiltration (e.g. /dev/shm).",
    },
    {
      technique_id: "T1567",
      technique_name: "Exfiltration Over Web Service",
      tactic: "Exfiltration",
      description: "Adversaries exfiltrate data through cloud storage, repositories, or external services.",
    },
  ],
  executive_summary: "Subject-Theta-482 exhibited persistent unanchored behavioral displacement spanning 14 days, accumulating recursive CUSUM drift S_t = 5.12. On Day 10, fabricated ticket JIRA-OPS-992 was rejected by CAS (0.18). On Day 13, access to simulated canary asset confirmed malicious intent deterministically. Escalated to Tier 4 Critical.",
  recommended_response_actions: [
    "Revoke active IAM assumed role and invalidate STS credentials immediately",
    "Isolate development workstation host 10.14.20.105 from VPC subnet",
    "Preserve volatile /dev/shm RAM disk forensic capture for chain-of-custody",
    "Convene Legal, DPO, and Works Council for Shamir 2-of-3 threshold unmasking ceremony",
  ],
  canary_status: MOCK_CANARY_STATUS,
  claim_label: "Measured Today",
};

export const MOCK_PRIVACY_VAULT_STATUS: PrivacyVaultStatus = {
  vault_status: "SEALED",
  threshold: "2-of-3",
  active_subjects_count: 48,
  demo_subject_token: "Subject-Theta-482",
  custodian_shares: [
    {
      custodian_role: "SOC_LEAD",
      custodian_name: "Marcus Vance (SOC Director)",
      index: 1,
      value_hex: "d471b058a3c9e6f2814a09c25381bcfe7a912e5410940ab653b194019a6b47c0",
    },
    {
      custodian_role: "DPO_LEGAL",
      custodian_name: "Sarah Chen, Esq. (Chief Privacy Officer)",
      index: 2,
      value_hex: "81e3a950f249c10842a7810b42c8d41095f32a017cb83e91459a105c317a80d5",
    },
    {
      custodian_role: "WORKS_COUNCIL",
      custodian_name: "Dr. Klaus Richter (Works Council Ombudsperson)",
      index: 3,
      value_hex: "29a7c4109d318e47b9520419e078345c6109fe2518a47b01934c5689104fa281",
    },
  ],
  reveals_count: 1,
  chain_head_hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  chain_integrity: "CRYPTOGRAPHICALLY_VERIFIED",
  active_harassment_alerts: 1,
  query_audits_count: 14,
  claim_label: "Measured Today",
};

export const MOCK_REVEAL_AUDIT_LOG: RevealReceipt[] = [
  {
    receipt_id: "REVEAL-C984B201",
    timestamp: "2026-09-14T09:15:30Z",
    subject_token: "Subject-Theta-482",
    unmasked_identity: "Elena Rostova (Staff Systems Engineer, EMP-84920)",
    participating_custodians: ["SOC_LEAD", "DPO_LEGAL"],
    justification: "Tier 4 Critical insider breach investigation authorized by Legal & Works Council",
    auditor_token: "DPO-Audit-Session-101",
    previous_receipt_hash: "0000000000000000000000000000000000000000000000000000000000000000",
    entry_hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    verified_chain: true,
    claim_label: "Measured Today",
  },
];

export const MOCK_HARASSMENT_ALERTS: HarassmentAlert[] = [
  {
    alert_id: "DPO-ALERT-2026-081",
    timestamp: "2026-09-12T11:20:00Z",
    subject_token: "Subject-Gamma-109",
    analyst_id: "SOC-Analyst-3",
    query_count: 4,
    window_days: 14,
    current_risk_tier: "TIER_1_CONTEXTUAL_DRIFT",
    status: "OPEN",
    dpo_notification: "Excessive manual inspection without risk tier escalation. Potential targeted employee surveillance.",
    claim_label: "Measured Today",
  },
];

export const MOCK_PROTECTED_RULES: ProtectedRule[] = [
  {
    rule_id: "RULE-WHISTLEBLOWER-URI",
    pattern: "*whistleblower*",
    category: "WHISTLEBLOWER",
    description: "All whistleblower portals and endpoints",
  },
  {
    rule_id: "RULE-OMBUDSMAN-DOMAIN",
    pattern: "*ombuds*",
    category: "OMBUDSMAN",
    description: "Ombudsman disclosure domains and mailboxes",
  },
  {
    rule_id: "RULE-ETHICS-HOTLINE",
    pattern: "*ethics*",
    category: "ETHICS_HOTLINE",
    description: "Corporate ethics hotlines and reporting forms",
  },
  {
    rule_id: "RULE-SPEAKUP-PORTAL",
    pattern: "*speakup*",
    category: "WHISTLEBLOWER",
    description: "SpeakUp external compliance intake portals",
  },
  {
    rule_id: "RULE-LEGAL-COUNSEL-EMAIL",
    pattern: "*external-counsel-disclosure@*",
    category: "LEGAL_COUNSEL",
    description: "External legal counsel privileged reporting",
  },
];
